### PR TITLE
No longer allocate temporary memory when serializing

### PR DESCRIPTION
**Pull request by lemire**
This might be faster than another PR:

https://github.com/RoaringBitmap/roaring/pull/246

### CODE REVIEW

**Comment by kevinconaway** [comment]
I will try this out on our workload and report back, thank you!

**Comment by lemire** [comment]
@kevinconaway Please do.

**Comment by kevinconaway** [comment]
@lemire I tested this out and it works great.  Thank you so much!  I will close my other PR

**Comment by lemire** [comment]
Tagged as a release.

**Pull request merged**
