### PR TITLE
Use Go 1.9 math/bits package

### PR DESCRIPTION
**Pull request by maciej**
This is a quick PR replacing bodies of `popcount` and `countTrailingZeros` functions to use Go 1.9 [math/bits](https://golang.org/pkg/math/bits/). Approaches fixing #101.

@lemire are there any other functions you had in mind to replace?

I'll post results of running `go test -bench Benchmark -run -` on relevant (of the Roaring functions that use the `popcnt` and `countTrailingZeros`) benchmarks from the current `master` and the PR branch soon. Do you think it's sufficient or should I write some specific benchmarks?

I have not inlined the `popcount` and `countTrailingZeros` functions themselves.

`popcount` gets inlined in `popcntSlice`:
```
TEXT %22%22.popcntSlice(SB) gofile../Users/maciejb/gowork/src/github.com/RoaringBitmap/roaring/popcnt.go
  popcnt.go:10		0x4b630			65488b0c2500000000	MOVQ GS:0, CX			[5:9]R_TLS_LE
  popcnt.go:10		0x4b639			483b6110		CMPQ 0x10(CX), SP		
  popcnt.go:10		0x4b63d			0f8685000000		JBE 0x4b6c8			
  popcnt.go:10		0x4b643			4883ec30		SUBQ $0x30, SP			
  popcnt.go:10		0x4b647			48896c2428		MOVQ BP, 0x28(SP)		
  popcnt.go:10		0x4b64c			488d6c2428		LEAQ 0x28(SP), BP		
  popcnt.go:10		0x4b651			31c0			XORL AX, AX			
  popcnt.go:10		0x4b653			488b4c2438		MOVQ 0x38(SP), CX		
  popcnt.go:10		0x4b658			31d2			XORL DX, DX			
  popcnt.go:12		0x4b65a			eb0a			JMP 0x4b666			
  popcnt.go:12		0x4b65c			4883c108		ADDQ $0x8, CX			
  popcnt.go:12		0x4b660			48ffc0			INCQ AX				
  popcnt.go:13		0x4b663			4801f2			ADDQ SI, DX			
  popcnt.go:12		0x4b666			488b5c2440		MOVQ 0x40(SP), BX		
  popcnt.go:12		0x4b66b			4839d8			CMPQ BX, AX			
  popcnt.go:12		0x4b66e			7d49			JGE 0x4b6b9			
  popcnt.go:12		0x4b670			488b31			MOVQ 0(CX), SI			
  popcnt.go:7		0x4b673			0fb63d00000000		MOVZX 0(IP), DI			[3:7]R_PCREL:runtime.support_popcnt
  popcnt.go:7		0x4b67a			4084ff			TESTL DI, DI			
  popcnt.go:7		0x4b67d			7407			JE 0x4b686			
  popcnt.go:7		0x4b67f			f3480fb8f6		POPCNT SI, SI			
  popcnt.go:7		0x4b684			ebd6			JMP 0x4b65c			
  popcnt.go:7		0x4b686			4889442418		MOVQ AX, 0x18(SP)		
  popcnt.go:7		0x4b68b			4889542410		MOVQ DX, 0x10(SP)		
  popcnt.go:7		0x4b690			48894c2420		MOVQ CX, 0x20(SP)		
  popcnt.go:7		0x4b695			48893424		MOVQ SI, 0(SP)			
  popcnt.go:7		0x4b699			e800000000		CALL 0x4b69e			[1:5]R_CALL:math/bits.OnesCount64
  popcnt.go:7		0x4b69e			488b742408		MOVQ 0x8(SP), SI		
  popcnt.go:7		0x4b6a3			488b442418		MOVQ 0x18(SP), AX		
  popcnt.go:7		0x4b6a8			488b4c2420		MOVQ 0x20(SP), CX		
  popcnt.go:7		0x4b6ad			488b542410		MOVQ 0x10(SP), DX		
  popcnt.go:7		0x4b6b2			488b5c2440		MOVQ 0x40(SP), BX		
  popcnt.go:7		0x4b6b7			eba3			JMP 0x4b65c			
  popcnt.go:15		0x4b6b9			4889542450		MOVQ DX, 0x50(SP)		
  popcnt.go:15		0x4b6be			488b6c2428		MOVQ 0x28(SP), BP		
  popcnt.go:15		0x4b6c3			4883c430		ADDQ $0x30, SP			
  popcnt.go:15		0x4b6c7			c3			RET				
  popcnt.go:10		0x4b6c8			e800000000		CALL 0x4b6cd			[1:5]R_CALL:runtime.morestack_noctxt
  popcnt.go:10		0x4b6cd			e95effffff		JMP %22%22.popcntSlice(SB)	
```

`countTrailingZeros` gets inlined even "deeper" with no calls to either `countTrailingZeros` or `bits.TrailingZeros64` in the output assembly:

```
TEXT %22%22.(*bitmapContainer).minimum(SB) gofile../Users/maciejb/gowork/src/github.com/RoaringBitmap/roaring/bitmapcontainer.go
  bitmapcontainer.go:50	0x3f291			488b442408		MOVQ 0x8(SP), AX	
  bitmapcontainer.go:50	0x3f296			31c9			XORL CX, CX		
  bitmapcontainer.go:51	0x3f298			eb03			JMP 0x3f29d		
  bitmapcontainer.go:51	0x3f29a			48ffc1			INCQ CX			
  bitmapcontainer.go:51	0x3f29d			488b5008		MOVQ 0x8(AX), DX	
  bitmapcontainer.go:51	0x3f2a1			488b5810		MOVQ 0x10(AX), BX	
  bitmapcontainer.go:51	0x3f2a5			4839d9			CMPQ BX, CX		
  bitmapcontainer.go:51	0x3f2a8			7d27			JGE 0x3f2d1		
  bitmapcontainer.go:52	0x3f2aa			488b14ca		MOVQ 0(DX)(CX*8), DX	
  bitmapcontainer.go:53	0x3f2ae			4885d2			TESTQ DX, DX		
  bitmapcontainer.go:53	0x3f2b1			74e7			JE 0x3f29a		
  ctz.go:40		0x3f2b3			480fbcc2		BSFQ DX, AX		
  bitmapcontainer.go:55	0x3f2b7			48c1e106		SHLQ $0x6, CX		
  ctz.go:40		0x3f2bb			480fbcd2		BSFQ DX, DX		
  ctz.go:40		0x3f2bf			ba40000000		MOVL $0x40, DX		
  ctz.go:40		0x3f2c4			480f44c2		CMOVE DX, AX		
  bitmapcontainer.go:55	0x3f2c8			4801c8			ADDQ CX, AX		
  bitmapcontainer.go:55	0x3f2cb			6689442410		MOVW AX, 0x10(SP)	
  bitmapcontainer.go:55	0x3f2d0			c3			RET			
  bitmapcontainer.go:58	0x3f2d1			66c7442410ffff		MOVW $-0x1, 0x10(SP)	
  bitmapcontainer.go:58	0x3f2d8			c3			RET			
```

### CODE REVIEW

**Comment by maciej** [comment]
Note this PR is currently replacing the current method implementations making `roaring` effectively incompatible with previous Go versions. I'll adapt it to be backward-compabile via build constraints in a subsequent commit

**Comment by maciej** [comment]
The last series of commits fixes _roaring_ for Go <1.9.

**Comment by maciej** [comment]
Here are a few selected benchmark results. All running on a late 2013 15’ MBP with Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz, 16GiB.

Results for `ctz`; current `master`:
```
Benchmark100CountTrailingZerosDeBruijn-8            	10000000	       121 ns/op
```
`go_bits`:
```
Benchmark100CountTrailingZerosDeBruijn-8            	30000000	        40.5 ns/op
```

Here are some results I picked from `benchmark_test.go`:
`master`:
```
BenchmarkIntersectionRoaring-8                      	 2000000	       832 ns/op
BenchmarkIntersectionCardinalityRoaring-8           	10000000	       200 ns/op
BenchmarkUnionRoaring-8                             	   10000	    185988 ns/op
BenchmarkSetRoaring-8                               	20000000	        58.0 ns/op
BenchmarkGetTestRoaring-8                           	20000000	       110 ns/op
BenchmarkCountRoaring-8                             	30000000	        41.6 ns/op
BenchmarkIterateRoaring-8                           	    2000	    787986 ns/op
BenchmarkSparseIterateRoaring-8                     	    2000	    657149 ns/op
BenchmarkSparseContains-8                           	   20000	     88323 ns/op
BenchmarkEqualsSparse-8                             	   20000	     85087 ns/op
BenchmarkXor-8                                      	    2000	    892965 ns/op
BenchmarkXorLopsided-8                              	   10000	    146650 ns/op
```

and `go_bits`:
```
BenchmarkIntersectionRoaring-8                      	 2000000	       844 ns/op
BenchmarkIntersectionCardinalityRoaring-8           	10000000	       204 ns/op
BenchmarkUnionRoaring-8                             	   10000	    186627 ns/op
BenchmarkSetRoaring-8                               	20000000	        57.5 ns/op
BenchmarkGetTestRoaring-8                           	20000000	       110 ns/op
BenchmarkCountRoaring-8                             	30000000	        41.9 ns/op
BenchmarkIterateRoaring-8                           	    2000	    760034 ns/op
BenchmarkSparseIterateRoaring-8                     	    2000	    675013 ns/op
BenchmarkSparseContains-8                           	   20000	     93251 ns/op
BenchmarkEqualsSparse-8                             	   20000	     84357 ns/op
BenchmarkXor-8                                      	    2000	    895347 ns/op
BenchmarkXorLopsided-8                              	   10000	    147452 ns/op
```

no huge differences here. @lemire perhaps I should write some microbenchmark for popcnt specifically. What do you think?

Full results: https://gist.github.com/maciej/7b7c76c288cce092be01c1a836e2bac1

**Comment by lemire** [comment]
Wow! Fantastic work...

It does feel like we could use more thorough benchmarks (if only because I am curious!). I'll try to find time to review all of this more carefully.

If anyone else wants to jump in, please do.

**Comment by maciej** [comment]
I wrote a simple `BenchmarkPopcount` based on `Benchmark100CountTrailingZerosDeBruijn`. Here are the results:

`go_bits`
```
BenchmarkPopcount-8   	20000000	        65.0 ns/op
```

`master`, actually [bench_popcount](https://github.com/maciej/roaring/tree/bench_popcount) branch
```
BenchmarkPopcount-8   	20000000	       121 ns/op

```
(note it's running the amd64 assembly)

**Comment by lemire** [comment]
For documentation purposes, let us recall that go1.9 means "go1.9 and following" and not, naively, "exactly version 1.9". (This is *not* an issue with the code, I just want to write it down.)

**Comment by brentp** [comment]
can you show the bench results with benchcmp? https://godoc.org/golang.org/x/tools/cmd/benchcmp

**Comment by cornelk** [comment]
Maybe we can name it ctz.go and ctz_pre_go1.9.go instead.

**Comment by lemire** [comment]
I am getting that the new version is significantly faster than the assembly code!

```
$ benchcmp oldwasm.txt new.txt
benchmark               old ns/op     new ns/op     delta
BenchmarkPopcount-2     97.6          61.1          -37.40%
```

On my machine, the assembly fares somewhat better than on @maciej's.

If we go naked without assembly, things are worse, evidently.

I think we should merge this, this is brilliant, but let us give people a chance to have a look.

**Comment by glycerine** [comment]
Lovely! Agree it would be nice if there was a way to say >=go1.9 so it doesn't break when people upgrade to go1.9.1 or tip. Otherwise LGTM.

**Comment by maciej** [comment]
@brentp I've added the `bechcmp` output in the [benchmark results gist](https://gist.github.com/maciej/7b7c76c288cce092be01c1a836e2bac1)

@glycerine the `//+build go1.9` directive means exactly that :-) It's go 1.9 an onwards https://golang.org/pkg/go/build/#hdr-Build_Constraints

I agree with @cornelk that perhaps we should name the Go 1.9-compatible source files as simply `popcnt.go` and `ctz.go`. I suggest we could suffix the current implementation source file names with `_compat`. What do you think about such naming?

**Comment by lemire** [comment]
The build directive is not intuitive, that's why I wanted to write down what it did. Not our fault though.

**Comment by lemire** [comment]
@maciej I agree regarding the naming convention update.

**Comment by maciej** [comment]
@lemire I renamed the files and commented the build constraints syntax. In addition to that I renamed the `Benchmark100CountTrailingZerosDeBruijn` to simply `Benchmark100CountTrailingZeros` benchmark function. Please have another look at the change set.

**Comment by lemire** [comment]
I will. It looks like we ought to merge this and issue a release soon.

**Comment by lemire** [comment]
@maciej Added your name to the authors file.

**Pull request merged**
