### PR TITLE
Add test for optimize then select

### PR DESCRIPTION
**Pull request by cryptix**
Select() returns different values after having called RunOptimize().

We hope this test and the data helps.

### CODE REVIEW

**Comment by lemire** [comment]
This is almost surely a bug then.

**Comment by lemire** [comment]
Let us mark this a priority.

**Comment by keks** [comment]
I tested this against 0.4.0, 0.3.0 and 0.2.0 and the test failed in all of them.

**Comment by lemire** [comment]
Merging to local branch for investigation.

**Comment by lemire** [comment]
The fix is there:

https://github.com/RoaringBitmap/roaring/pull/238

Will be merged shortly. 

This was a real, off-by-one bug.

**Comment by lemire** [comment]
I am issuing a new release just now, please update, and verify.

**Pull request merged**
