### PR TITLE
Implement arena allocation for frozen views

### PR DESCRIPTION
**Pull request by Oppen**
This turns the five allocations used to support containers in frozen views into a single big one.
I'm not 100% it's worth the extra code complexity, but reviewers will judge that :)

### CODE REVIEW

**Comment by lemire** [comment]
@Oppen Do you have some quantification of the potential benefits.

**Comment by Oppen** [comment]
In abstract, it lowers number of allocations to 1/5.
In concrete, I can write a simple test case similar (but not quite the same) as what my project does, just the serialization part only, and profile that (I know that for the whole deal the GC takes a big part of the CPU, it's possible but not confirmed that serialization is a sizable contributor to this).
The overly simplified example would just create a single random but dense bitmap and serialize it 100k times. That's because it's in the order of what I'm dealing with.
Then, comparing profiles before and after would tell us how much of an effect this had.
Does that sound reasonable?

**Comment by lemire** [comment]
> In abstract, it lowers number of allocations to 1/5.

In C, that would be a win under many systems, but I am not sure whether it is a win in Go because it comes with added complexity. 

> The overly simplified example would just create a single random but dense bitmap and serialize it 100k times. That's because it's in the order of what I'm dealing with.

Right. Basically, this PR increases the complexity of the code and makes maintainability a bit harder. That is fine if there is a clear performance benefit, and if there is, then you'd want to be able to illustrate it with an example, even an artificial-looking one.

**Comment by richardartoul** [comment]
… does this FrozenView functionality work for bitmaps that’s were serialized using this library? I have a custom storage system / database workload that is unfortunately not open source, but involves “compacting” many bitmaps from input files into output bitmaps in an output file.

For some reason the FrozenView function doesn’t show up in the go doc. If I could use that in my workload, then this P.R would result in a huge reduction in allocations for me. Maybe I can try and benchmark and provide some numbers?

**Comment by richardartoul** [comment]
Ok I got some benchmarks for ya :D

Using standard binary format:

```
// goos: darwin
// goarch: amd64
// pkg: github.com/DataDog/dd-go/logs/apps/logs-event-store/postings
// cpu: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
// BenchmarkSerialize/small/serialize-8         	 6919682	       159.5 ns/op	     128 B/op	       3 allocs/op
// BenchmarkSerialize/small/deserialize-8       	12045405	        93.53 ns/op	      24 B/op	       1 allocs/op
// BenchmarkSerialize/sparse/serialize-8        	  588884	      2154 ns/op	    5768 B/op	       5 allocs/op
// BenchmarkSerialize/sparse/deserialize-8      	 6148747	       167.1 ns/op	      48 B/op	       2 allocs/op
// BenchmarkSerialize/dense/serialize-8         	  355005	      3021 ns/op	    9616 B/op	       5 allocs/op
// BenchmarkSerialize/dense/deserialize-8       	 6455646	       171.4 ns/op	      56 B/op	       2 allocs/op
```

Using frozen format (v1.1 code)
```
// goos: darwin
// goarch: amd64
// pkg: github.com/DataDog/dd-go/logs/apps/logs-event-store/postings
// cpu: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
// BenchmarkSerialize/small/serialize-8         	21922633	        49.17 ns/op	      16 B/op	       1 allocs/op
// BenchmarkSerialize/small/deserialize-8       	10731942	       110.9 ns/op	      41 B/op	       3 allocs/op
// BenchmarkSerialize/sparse/serialize-8        	 2207445	       545.4 ns/op	    2048 B/op	       1 allocs/op
// BenchmarkSerialize/sparse/deserialize-8      	 6976035	       170.2 ns/op	      82 B/op	       3 allocs/op
// BenchmarkSerialize/dense/serialize-8         	  529496	      2007 ns/op	    9472 B/op	       1 allocs/op
// BenchmarkSerialize/dense/deserialize-8       	 6715400	       176.2 ns/op	      90 B/op	       4 allocs/op
```

Using frozen format + the code from this P.R
```
// goos: darwin
// goarch: amd64
// pkg: github.com/DataDog/dd-go/logs/apps/logs-event-store/postings
// cpu: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
// BenchmarkSerialize/small/serialize-8         	20090436	        52.59 ns/op	      16 B/op	       1 allocs/op
// BenchmarkSerialize/small/deserialize-8       	14191478	        85.44 ns/op	      48 B/op	       1 allocs/op
// BenchmarkSerialize/sparse/serialize-8        	 2049729	       560.9 ns/op	    2048 B/op	       1 allocs/op
// BenchmarkSerialize/sparse/deserialize-8      	12641308	        99.07 ns/op	      96 B/op	       1 allocs/op
// BenchmarkSerialize/dense/serialize-8         	  516709	      2085 ns/op	    9472 B/op	       1 allocs/op
// BenchmarkSerialize/dense/deserialize-8       	12202070	        97.56 ns/op	      96 B/op	       1 allocs/op
```

Also the experimentation I did showed that my file actually got *smaller* with the frozen format.

Those are some serious performance gains. I think that justifies a little extra complexity!

**Comment by richardartoul** [comment]
@lemire @Oppen

**Comment by lemire** [comment]
Let us consider it for inclusion given @richardartoul recommendation.

This functionality is not well documented and it does not appear in go doc. That is something that could be fixed in the future, but it is also the case that we do not want to 'push' this feature. It is only meant for advanced users.

**Comment by lemire** [comment]
Let us include it in our next release.

**Pull request merged**
