### PR TITLE
Added MinMax() function.

### PR DESCRIPTION
**Pull request by guymolinari**
Added new Min/Max BSI value feature.

### CODE REVIEW

**Comment by lemire** [comment]
It seems that the code fails your tests...

```
--- FAIL: TestMinMaxWithNegative (0.00s)
    bsi64_test.go:412: 
        	Error Trace:	bsi64_test.go:412
        	Error:      	Not equal: 
        	            	expected: -5
        	            	actual  : -4
        	Test:       	TestMinMaxWithNegative
    bsi64_test.go:413: 
        	Error Trace:	bsi64_test.go:413
        	Error:      	Not equal: 
        	            	expected: 5
        	            	actual  : 4
        	Test:       	TestMinMaxWithNegative
```

**Comment by guymolinari** [comment]
Looks like another platform related issue.

**Comment by guymolinari** [comment]
Damn.   I had a test commented out.   I'll fix.

**Comment by lemire** [comment]
Looks good to me. Merging.

**Pull request merged**
