### PR TITLE
fix use nil parameter, the MinMaxBig func will throw panic's problem

### PR DESCRIPTION
**Pull request by ChicChip**
i fixed fix use nil parameter, the MinMaxBig func will throw panic's problem (https://github.com/RoaringBitmap/roaring/issues/455)

### CODE REVIEW

**Comment by guymolinari** [comment]
Could you also look at CompareBigValue ad well?

**Comment by ChicChip** [comment]
in bsi64.go and bsi.go file, if foundSet is nil, is it all set to exisitence bitmap?

**Comment by ChicChip** [comment]
i think these function may all hava nil pointer problem when parameter is nil

1. TransposeWithCounts
2. SumBigValues
3. IntersectAndTranspose
4. TransposeWithCounts
5. Increment

**Comment by guymolinari** [comment]
Yes.  Also in CompareBigValue.  If 'end' is not set it will panic also

**Comment by ChicChip** [comment]
> i think these function may all hava nil pointer problem when parameter is nil
> 
> 1. TransposeWithCounts
> 2. SumBigValues
> 3. IntersectAndTranspose
> --4. TransposeWithCounts
> 5. Increment

I have set default value for these function, include CompareBigValue

**Pull request merged**
