### PR TITLE
add flushCopyOnWrite() call so that source bitmaps can be unmapped.

### PR DESCRIPTION
**Pull request by jacksonrnewhouse**
This adds FlushCopyOnWrite() to address https://github.com/RoaringBitmap/roaring/issues/219. Interested in hearing what testing we should be doing. Also, I think it is right not to touch the roaring array's CopyOnWrite field. Is that correct?

@lemire @maciej

### CODE REVIEW

**Comment by lemire** [comment]
Thank you for the PR.


We need a test!

Can you have a look at this new test I added...


https://github.com/RoaringBitmap/roaring/blob/master/serialization_test.go#L931-L964

This line...

```
rbor2 := rbor1.Clone()
```

could be replaced by a new safer approach.

```
rbor2 := rbor1.flushCopyOnWrite()
```

Can you add a comment to describe what the function is expected to do.

**Comment by jacksonrnewhouse** [comment]
Updated it with some tests, comments and a better name.

**Comment by lemire** [comment]
This is good. Really good.

Let us merge. There is no risk as far as I can tell.

**Comment by maciej** [comment]
looks good to me too.

**Pull request merged**
