### PR TITLE
Add 64 bit implementation of roaring.Bitmap

### LINKED ISSUE #136: Support 64-bit indices?
If it isn't already (- I may have missed it), are there any plans to support 64 bit indices ala `Roaring64NavigableMap` from the java implementation? Is it hard to do in practice?

### PR DESCRIPTION
**Pull request by jacobmarble**
Fixes #136

This PR is very much a work-in-progress. I've tried to stay with the original 32 bit method signatures as much as possible. Serialization is explicitly not part of this PR.

- [x] fix failing tests
- [x] augment tests with 64 bit values
- [x] verify copy-on-write

### CODE REVIEW

**Comment by jacobmarble** [comment]
@lemire do you mind giving this an early review? I want to make sure I'm on the right track.

**Comment by lemire** [comment]
@jacobmarble  This looks like solid code to me. It ressembles the C++ and Java counterparts of the same design.

Obviously, I can only encourage the addition of more testing, and if you are able, I'd throw in fuzz testing as well.

**Comment by kevinconaway** [comment]
Any update here?

**Comment by lemire** [comment]
@kevinconaway There are some tests and it looks good, but the tests are not as thorough as one would like. I am nervous about merging this and having people's database blow up. We also could use performance and memory usage measures.

Would you be willing to add new tests and take it out on a spin?

**Comment by lemire** [comment]
This issue  https://github.com/RoaringBitmap/roaring/issues/252 might reference this PR.

**Comment by guymolinari** [comment]
This work is really needed.   Can I help in some way?

**Comment by lemire** [comment]
@guymolinari  Yes. Can you review and test this PR?

There are tests, but I concerned that they may not be thorough enough. We don't want this code to blow up when it goes into production.

**Comment by guymolinari** [comment]
Will do @lemire.   Have a large project with 100s of terabytes of data that will use this.

**Comment by jacobmarble** [comment]
Thanks for the chatter here. I wrote what is here so far and then got busy with other work.

**Comment by guymolinari** [comment]
How do you wan't to handle this @jacobmarble?   I will definitely need the serialization stuff and am willing to dig in and do it.   Also, more tests as needed.   I have another outstanding PR with @lemire so I'm not sure working on my fork would make sense.   Never forked another owners fork.   Should I go this route?

**Comment by jacobmarble** [comment]
You could pull down my branch and layer new commits on top, or cherry pick them into your branch. It would be nice to see my name on my commits, but that's all.

**Comment by guymolinari** [comment]
@jacobmarble Could you grant write permissions to me for this repo?

**Comment by jacobmarble** [comment]
@guymolinari I've added you as a collaborator, see if that works

**Comment by guymolinari** [comment]
Getting a 403 response

**Comment by guymolinari** [comment]
Actually,  I had to accept the invitation first.   I can now push a new
branch.

Thanks,
Guy

**Comment by lemire** [comment]
@guymolinari Keep us posted.

**Comment by guymolinari** [comment]
Will do @lemire @jacobmarble.   Should have an update tomorrow.   Next step is to increase test coverage and then should be ready to integrate with my project.

**Comment by guymolinari** [comment]
I'm checking in test cases and coverage percentage is dropping.   I'm going to call it good for now and move on to integrating the 64 bit version into my project and see how it works.   We should have functional parity between the legacy and 64 bit APIs.

1) Serialization should be done.   Looking at the C/C++ CRoaring libraries I have tried to follow the established patterns (word sizes, endianness, etc) so that wire protocols and cross language polyglots are preserved.

2) Added some tests that focus on 64 bit values for better coverage.   Unable to fool the static analysis being done by Coverall.   :-)

Cheers,
Guy

  @lemire  @jacobmarble

**Comment by guymolinari** [comment]
@lemire @jacobmarble The roaring64 implementation is missing the ParOr function so I will have to add that.   It is required for my project and also the new PR for the bit slice indexing library.   @lemire I guess we have a separate 64 bit version of that as well?

**Comment by lemire** [comment]
Great work.

> The roaring64 implementation is missing the ParOr function so I will have to add that. It is required for my project

Is that blocking for you, or something you can add later?

> I guess we have a separate 64 bit version of that as well? 

Can your rephrase?

>  and also the new PR for the bit slice indexing library.

I am not forgetting that PR, but let us keep things separate for now.

**Comment by guymolinari** [comment]
@lemire It is a blocker but not for long.   I'll implement in the next
day or two.   I have some large data sets to process and will have a good
idea of processing times and can verify correctness against another system
of record.

**Comment by guymolinari** [comment]
@lemire @jacobmarble I am happy to say that application level testing went well.

I upgraded my system to utilize the new 64 bit library and processed about 1TB of data.   I tested under 2 scenarios.  Both results were compared against the system of record without issue.    Another thing of note.   I had to create a 64 bit version of the new BSI library as well as it is also heavily utilized (will submit a separate PR when you are ready @lemire).   

1) The first scenario used 32 bit identifiers.   Processing latency was on par with the legacy 32 bit version.

2) The second scenario involved generating 64 bit identifiers by doing a 32 bit shift left and adding a timestamp.   Processing time increased as expected (almost 3x).   Not really surprised but I'm wondering if it would make sense to move away from an array of slices ([]*roaring.Bitmap) and use a (map[]*roaring.Bitmap) in order to mitigate the overhead of binarySearch().

Either way I think this is a +1 from my perspective.   Additional test coverage would be nice.   Also, a few features need to be ported to 64 bit as well.

**Comment by lemire** [comment]
@guymolinari  Note that I merged the BSI code and then applied maintenance on it.

**Comment by lemire** [comment]
@guymolinari Did we test the COW functionality at some point?

**Comment by guymolinari** [comment]
Awesome.

**Comment by guymolinari** [comment]
I do believe I added some related tests.  I'll double check this evening.

**Comment by guymolinari** [comment]
@lemire I moved the COW tests from roaring into roaring64.   One of the
tests is failing so I'm looking at fixing the bug.   This is just testing
the 64 bit API but not 64 bit values.    After I fix the issue I will look
at expanding this to 64 bit values.

**Comment by lemire** [comment]
@guymolinari Any update?

**Comment by guymolinari** [comment]
Hello @lemire,
    Things are looking pretty good (I think).   There are a few higher
level features (FastAnd, HeapOr, etc.) that haven't been migrated to 64 bit
yet.   Not sure if we need these to get the PR over the finish line or
not.  I do have a 64 bit version of BSI that I haven't teed up a PR for yet.

Let me know what I can do to help.

**Comment by lemire** [comment]
@guymolinari If you could just let us know whether you recommend that the PR be merged, that would be great. If you do, I will then review it and hopefully merge it soon after.

Missing features that you do not consider essential are ok. They can come later.

**Comment by guymolinari** [comment]
This is all additive.   It works.   Test coverage passes.
+1 to review and merge
@lemire for review

**Comment by lemire** [comment]
It looks good to me. I will merge and possibly do some minor edits.

**Pull request merged**
