### PR TITLE
Add Iterate() method for iterating the bitmap without an iterator

### PR DESCRIPTION
**Pull request by kevinconaway**
One of our applications currently makes heavy use of Iterators.  We noticed that they are a minor but noticeable source of allocations (along with the associated cpu & gc cost) in our application due to each Iterator being heap allocated along with the internal iterators each container creates.

This commit provides an alternate Iterate() method with a callback that iterates the bitmap in place, invoking the callback for each value.  This avoids allocations entirely at the cost of some code duplication

Below are benchmarks, you can see that `iterate` doesn't allocate and is slightly faster.

```
$ go test -run=none -bench=BenchmarkIterateRoaring -count 25

$ benchstat
name                                  time/op
IterateRoaring/iterator-compressed-8  519µs ± 3%
IterateRoaring/iterator-8             517µs ± 4%
IterateRoaring/iterate-compressed-8   349µs ± 4%
IterateRoaring/iterate-8              347µs ± 3%

name                                  alloc/op
IterateRoaring/iterator-compressed-8  96.0B ± 0%
IterateRoaring/iterator-8             96.0B ± 0%
IterateRoaring/iterate-compressed-8   0.00B
IterateRoaring/iterate-8              0.00B

name                                  allocs/op
IterateRoaring/iterator-compressed-8   4.00 ± 0%
IterateRoaring/iterator-8              4.00 ± 0%
IterateRoaring/iterate-compressed-8    0.00
IterateRoaring/iterate-8               0.00
```

@lemire please let me know your thoughts, I'm open to alternatives as well.

### CODE REVIEW

**Comment by lemire** [comment]
This looks reasonable. Both the C++ and Java roaring counterparts have the same idea. In C++, it can help tremendously performance-wise.

**Comment by lemire** [comment]
@alldroll : want to have a look?

**Comment by alldroll** [comment]
Thank you for your PR!

I do concern about duplicating logic. Maybe we can reuse it and use memory allocation on stack? Here is my draft

```go
func (ac *arrayContainer) init(iterator *shortIterator) {
       iterator.slice = ac.content
       iterator.loc = 0
}

func (bc *bitmapContainer) init(iterator *bitmapContainerShortIterator) {
       iterator.ptr = bc
       iterator.i = bc.NextSetBit(0)
}

func (rc *runContainer16) init(iterator *runIterator16) {
       iterator.rc = rc
       iterator.curIndex = 0
      iterator.curPosInIndex = 0
}

func (rb *Bitmap) Iterate(cb func(x uint32) bool) {
	var (
		hs             uint32
		c              container
		arrayIterator  = shortIterator{}
		runIterator    = runIterator16{}
		bitmapIterator = bitmapContainerShortIterator{}
	)

	for i := 0; i < rb.highlowcontainer.size(); i++ {
		hs = uint32(rb.highlowcontainer.getKeyAtIndex(i)) << 16
		c = rb.highlowcontainer.getContainerAtIndex(i)

		// This is hacky but it avoids allocations from invoking an interface method with a closure
		switch t := c.(type) {
		case *arrayContainer:
			t.init(&arrayIterator)

			for arrayIterator.hasNext() {
				x := arrayIterator.next()
				cb(uint32(x) | hs)
			}
		case *runContainer16:
			t.init(&runIterator)

			for runIterator.hasNext() {
				x := runIterator.next()
				cb(uint32(x) | hs)
			}
		case *bitmapContainer:
			t.init(&bitmapIterator)

			for bitmapIterator.hasNext() {
				x := bitmapIterator.next()
				cb(uint32(x) | hs)
			}
		default:
			break
		}

	}
}
```

The most important here that we don't replicate the iteration logic as it could be complicated. (please take a look at  `func (rc *runContainer16) iterate(cb func(x uint16) bool) bool`

What do you think about it?

**Comment by kevinconaway** [comment]
LGTM.  The benchmarks don't really change

```
name                                  time/op
IterateRoaring/iterator-compressed-8  551µs ± 8%
IterateRoaring/iterator-8             559µs ± 4%
IterateRoaring/iterate-compressed-8   355µs ± 7%
IterateRoaring/iterate-8              346µs ± 7%

name                                  alloc/op
IterateRoaring/iterator-compressed-8  96.0B ± 0%
IterateRoaring/iterator-8             96.0B ± 0%
IterateRoaring/iterate-compressed-8   0.00B
IterateRoaring/iterate-8              0.00B

name                                  allocs/op
IterateRoaring/iterator-compressed-8   4.00 ± 0%
IterateRoaring/iterator-8              4.00 ± 0%
IterateRoaring/iterate-compressed-8    0.00
IterateRoaring/iterate-8               0.00
```

If you're satisfied with that approach I will incorporate it in the PR

**Comment by alldroll** [comment]
Yes, of course. Let's ask @lemire what he thinks about it. For me, a better approach is hybrid with your solution:

```go
func (ac *arrayContainer) iterate(cb func(x uint16) bool) bool {
	iterator := shortIterator{ac.content, 0}

	for iterator.hasNext() {
		if !cb(iterator.next()) {
			return false
		}
	}

	return true
}

func (bc *bitmapContainer) iterate(cb func(x uint16) bool) bool {
	iterator := bitmapContainerShortIterator{bc, bc.NextSetBit(0)}

	for iterator.hasNext() {
		if !cb(iterator.next()) {
			return false
		}
	}

	return true
}

func (rc *runContainer16) iterate(cb func(x uint16) bool) bool {
	iterator := runIterator16{rc, 0, 0}

	for iterator.hasNext() {
		if !cb(iterator.next()) {
			return false
		}
	}

	return true
}

func (rb *Bitmap) Iterate(cb func(x uint32) bool) {
	var (
		hs             uint32
		c              container
		shouldContinue bool
	)

	for i := 0; i < rb.highlowcontainer.size(); i++ {
		hs = uint32(rb.highlowcontainer.getKeyAtIndex(i)) << 16
		c = rb.highlowcontainer.getContainerAtIndex(i)

		// This is hacky but it avoids allocations from invoking an interface method with a closure
		switch t := c.(type) {
		case *arrayContainer:
			shouldContinue = t.iterate(func(x uint16) bool {
				return cb(uint32(x) | hs)
			})
		case *runContainer16:
			shouldContinue = t.iterate(func(x uint16) bool {
				return cb(uint32(x) | hs)
			})
		case *bitmapContainer:
			shouldContinue = t.iterate(func(x uint16) bool {
				return cb(uint32(x) | hs)
			})
		default:
			break
		}

		if !shouldContinue {
			break
		}
	}
}

```

**Comment by kevinconaway** [comment]
That looks good to me as well.  I'm happy to implement whatever you all decide.

**Comment by alldroll** [comment]
Let's do a hybrid version. Thank you!

**Comment by kevinconaway** [comment]
Updated.  Benchmarks remain stable

```
name                                  time/op
IterateRoaring/iterator-compressed-8  743µs ±316%
IterateRoaring/iterator-8              547µs ±13%
IterateRoaring/iterate-compressed-8    366µs ± 6%
IterateRoaring/iterate-8               364µs ± 9%

name                                  alloc/op
IterateRoaring/iterator-compressed-8   96.0B ± 0%
IterateRoaring/iterator-8              96.0B ± 0%
IterateRoaring/iterate-compressed-8    0.00B
IterateRoaring/iterate-8               0.00B

name                                  allocs/op
IterateRoaring/iterator-compressed-8    4.00 ± 0%
IterateRoaring/iterator-8               4.00 ± 0%
IterateRoaring/iterate-compressed-8     0.00
IterateRoaring/iterate-8                0.00
```

**Comment by lemire** [comment]
That last version is actually pretty clever.

**Comment by kevinconaway** [comment]
Team work makes the dream work.  Thank you for @alldroll for taking the time to make this better.

**Comment by joenall** [comment]
Is there a benchmark that shows decreased allocations?

**Comment by kevinconaway** [comment]
@joenall The `benchstat` output above shows it.  The first block is the CPU time, the second block is the number of bytes allocated  and the third block is the number of allocations 

You can see that the `iterate` benchmarks have 0 bytes allocated/op and 0 allocations/op

Does that make sense?

**Comment by lemire** [comment]
@kevinconaway Note that there is one "obvious" way to make this even better. If you write a function that operates over slices instead of individual values, then we can repurpose the `ManyIntIterable` construct. You would have a function just like the one you have now, except that it would receive a slice with each call. For some applications, it could be several times faster.

Still. This change here is very neat and it has proven itself. Let us merge.

**Comment by lemire** [comment]
Credit to @alldroll  for the thorough review.

**Pull request merged**
