### PR TITLE
roaring64.go: fix uint64 print.

### PR DESCRIPTION
**Pull request by JinLingChristopher**
This is a bug fix for #270 , PTAL.

### CODE REVIEW

**Comment by lemire** [comment]
@guymolinari  Can you have a look?

**Comment by JinLingChristopher** [comment]
travis-ci failed ? does this matter ?

**Comment by lemire** [comment]
Probably not. A dependency we use for testing does not support older
versions of Go. The authors were too eager to upgrade.

**Review by guymolinari — APPROVED** [review]

**Comment by lemire** [comment]
Merging.

**Pull request merged**
