### PR TITLE
Report heap use as metrics in benchmark

### PR DESCRIPTION
**Pull request by Oppen**
This should help `benchstat` and `benchcmp` to avoid getting confused by spurious prints in the output.

### CODE REVIEW

**Comment by Oppen** [comment]
That method is not implemented before Go 1.13 😢

**Comment by Oppen** [comment]
Is this worth a build tag?

**Comment by lemire** [comment]
@Oppen 

> Is this worth a build tag?

It might be. There are still production systems running 1.10... we don't test for that, but 1.11 is really not that old.

**Comment by lemire** [comment]
@Oppen Yes!

**Comment by lemire** [comment]
Great work. Merging.

**Pull request merged**
