### PR TITLE
Port Java version of array-run container intersection algorithm

### PR DESCRIPTION
**Pull request by maciej**
This PR ports the [Java version of the array-run intersection algorithm](https://github.com/RoaringBitmap/RoaringBitmap/blob/43e3f466af230945eb8bc4abd60dc557a3e9e6d7/roaringbitmap/src/main/java/org/roaringbitmap/RunContainer.java#L300). In a private benchmark the performance improves significantly.

### CODE REVIEW

**Comment by lemire** [comment]
Presumably, we are waiting on the previous PRs to be merged.

**Comment by maciej** [comment]
@lemire yes, that's correct. I cherry-picked the commits onto `master` without realizing that I'm relying on the code from the other PRs. :-)

**Comment by lemire** [comment]
That's totally a fine thing to do, my comment has more to do with documentation than anything else.

**Comment by lemire** [comment]
This can now be merged. We'll issue a release.

**Pull request merged**
