### PR TITLE
Support CRoaring's frozen format

### LINKED ISSUE #318: Support CRoaring's frozen format for interoperability
Doing this would mean the pure Go implementation can be used to create bitmaps to later be used by a more restricted environment, such as one using Python or C, while still being able to memory map the contents.
Using the pure Go version introduces several advantages versus using GoCRoaring, such as better memory accounting and parallel operations, as well as the ability to use scratch-images when deploying in Docker.
Is there any interest in this functionality? I could try to implement it, I just want to know if it'll be rejected in principle.

Note this isn't about performance and there will be a penalty; there would be a comment in the documentation noting that this should only be used for interoperability, never where performance matters.

### PR DESCRIPTION
**Pull request by Oppen**
Resolves #318

### CODE REVIEW

**Comment by lemire** [comment]
@Oppen LGTM complains about a useless variable assignment.

**Comment by Oppen** [comment]
I forgot to `git add` the tests 🤦

**Comment by lemire** [comment]
@Oppen Can you have a look at the failed tests.

**Comment by Oppen** [comment]
Oddly enough, it complains about gocroaring having unmet build constraints (I'm using it in the tests to build the reference frozen bitmap). I found none in the code.

**Comment by lemire** [comment]
@Oppen I do not think that the tests can depend on `real-roaring-datasets`. That's a 166 megabyte repository. I am not sure users would like to have it as a dependency. Now... it might be perfectly allowable if the repository does exist (because the user otherwise pulled) and GOPATH is configured.

I mean... maybe I am wrong, but I did not expect anyone to ever depend on `real-roaring-datasets`. Now... a subset of that could make sense, or an optional test...

**Comment by lemire** [comment]
> Oddly enough, it complains about gocroaring having unmet build constraints (I'm using it in the tests to build the reference frozen bitmap). I found none in the code.

Do we expect Go to support C linkage when run in cross-compile mode (e.g., `GOARCH=386 go test`)?

The larger issue is that I do not think we want our tests to depend on gocroaring. That's probably going to add much overhead to the tests.

What I suggest to do is just to create one or two, or just a few, representative frozen binary files. We have a few of those. Make sure it is small. Then we can just check that we can read and map it.

There is no need to gather megabytes of data files, create new frozen serialization using gocroaring and then check that we can read them back in `roaring`. I mean, sure, as one test the thing initially and maybe optionally, this makes sense, but we don't want all users type `go test` to go through that pain.


We really, really, really want `go test` to be fast. It is a quality-of-life issue. Nobody wants to hack code that takes forever to test.

Extensive tests *are* important, but routine tests must be fast.

**Comment by Oppen** [comment]
OK, I'll just serialized bitmaps like the ones in the tests in both formats (it seems odd to have hardcoded the ones in memory) and possibly some randomized ones.

**Comment by Oppen** [comment]
Updated with new tests based on prebuilt bitmaps.

**Comment by lemire** [comment]
This is beautiful work. If you recommend merging at this time, I will do so right away and issue a new release.

**Comment by Oppen** [comment]
I think it's mergeable but I'd like to try to work in a few more issues over the weekend, so maybe wait until Monday for the release.

**Comment by lemire** [comment]
@Oppen There is no rush to merge if we are not going to release, so let us give it a few days.

(It is highly unlikely that some other code change would create a conflict, so we can afford to leave the PR open quite a bit.)

**Comment by Oppen** [comment]
OK, I didn't make as much progress during the weekend as I expected (mainly I focused on trying to make `FastAnd` a bit better than doing two-by-two and saw gains too small to justify the complexity and the extra memory usage; I'll PR the benchmark later as a reminder for future self that that's fast enough) and during I don't think I'll do much until next weekend. So releasing is fine with me :)

**Comment by lemire** [comment]
Merging.

**Pull request merged**
