### PR TITLE
fixes the int overflow

### PR DESCRIPTION
**Pull request by 0x4139**
regarding the issue #85

### CODE REVIEW

**Comment by lemire** [comment]
@0x4139  

I am concerned with your commit "moves the utility functions away from the file with conditional builds". 

https://github.com/RoaringBitmap/roaring/pull/87/commits/f341b887fd0371f395ee8c8e9104313bdf7d5516

I don't think it is correct because the Roaring format requires all words to be written using little endian encoding...

https://github.com/RoaringBitmap/RoaringFormatSpec#general-layout

The proper fix here is that uint64SliceAsByteSlice and uint16SliceAsByteSlice should be "file private" to https://github.com/RoaringBitmap/roaring/blob/master/serialization_littleendian.go and never called elsewhere.

c.c. @glycerine

**Comment by 0x4139** [comment]
@lemire you might be right, it's my first time i am seing the code, but doing so we need to make some other module

**Comment by lemire** [comment]
@0x4139  For now, I just suggest you remove this commit from the PR, so we can address the issue separately.

Also, please add your name to https://github.com/RoaringBitmap/roaring/blob/master/AUTHORS

**Comment by lemire** [comment]
@0x4139  I don't think we need a new module, we just need to change @glycerine 's recent changes so that we avoid the calls to ``uint64SliceAsByteSlice`` and ``uint16SliceAsByteSlice``. They should not have been allowed in... but I missed it. My fault. Thankfully, it is not hard to fix.

**Comment by lemire** [comment]
To be clear, you should add your name to https://github.com/RoaringBitmap/roaring/blob/master/CONTRIBUTORS

**Comment by lemire** [comment]
@0x4139  If the PR is still relevant, please rebase with master.

**Comment by glycerine** [comment]
this was addressed in #84; you can close without merging.

**Comment by lemire** [comment]
@0x4139  Ok. I am going to close this. Reopen a new PR if needed.

**Pull request closed without merging**
