### PR TITLE
Keep header.Data alive during unsafe operations

### PR DESCRIPTION
**Pull request by jacksonrnewhouse**
While not likely to occur in the wild, changes to how gc inlines functions in 1.12 creates the possibility for data loss when serialization_littleendian.go uses unsafe to change the type of slices. I've added a unit test that will fail on 1.12.7 without the other changes in this package. This addresses the issues I raised in https://github.com/RoaringBitmap/roaring/issues/224.

### CODE REVIEW

**Comment by lemire** [comment]
We need someone to review this.

@maciej @statik @glycerine ???

**Comment by maciej** [comment]
@jacksonrnewhouse the `KeepAlive` indeed is needed. Thank you for adding that.

Could you please explain why the `inlined` test fails and does so fairly consistently? I struggle to understand that looking only at the code.

Would you mind squashing your commits? It makes for an easier to read git history later.

**Comment by lemire** [comment]
@maciej  We can squash commits during the merge.

**Comment by lemire** [comment]
@maciej Otherwise, do you approve the PR? (I will squash.)

**Comment by maciej** [comment]
@lemire I'd like to see a comment or two on the test case. Otherwise the change in code is the right one – I approve of it. KeepAlive is indeed needed.

**Comment by alldroll** [comment]
I am not sure, but we should do `runtime.KeepAlive(slice)` instead of `header.Data` as described here https://go101.org/article/unsafe.html

**Comment by lemire** [comment]
Can someone address @alldroll ‘s point?

**Comment by maciej** [comment]
I haven't yet read the article that was linked to in the previous comment, however:

godoc has the following note on `reflect.SliceHeader`:
> […] the Data field is not sufficient to guarantee the data it references will not be garbage collected, so programs must keep a separate, correctly typed pointer to the underlying data.

https://golang.org/pkg/reflect/#SliceHeader

So @alldroll you are probably right. As long as we satisfy the requirement of keeping a reference to `header.Data` we don't keep it as a correctly typed pointer.

**Comment by jacksonrnewhouse** [comment]
Yeah, it should be saving a pointer to the slice

**Comment by lemire** [comment]
@jacksonrnewhouse Want to update the PR accordingly?

**Comment by lemire** [comment]
Ping!

**Comment by lemire** [comment]
Merging to a side branch given that the original author is not responding.

**Pull request merged**
