### PR TITLE
Update roaring64.go

### PR DESCRIPTION
**Pull request by hyhanyan**
modify roaring GetSizeInBytes bug

### CODE REVIEW

**Comment by lemire** [comment]
Looks reasonable.

**Comment by lemire** [comment]
Does someone want to comment ?

**Comment by hyhanyan** [comment]
What to do next ？

**Comment by lemire** [comment]
We will handle it from here. Thanks.

**Comment by hyhanyan** [comment]
> We will handle it from here. Thanks.

What about merging at this time?

**Pull request merged**
