### PR TITLE
make arrayContainer's iorArray optimistic.

### PR DESCRIPTION
**Pull request by jacksonrnewhouse**
The current code for arraycontainers' iorArray method is pessimistic about the likelihood of the union staying under 4096. If the sum of cardinalities is greater than 4096 it creates a bitmap container, iterates over each container, flipping bits as appropriate. Then, if the final size is <=4096, it converts it back to an array container.

This change makes this operation optimistic, checking only after taking the union to see if it should be a bitmap. As you can see from the benchmarks, neither approach is dominant. If you need a bitmap, better to just convert to start with. However, if the result is still an array, you save a bunch of time by never involving bitmaps. 

I think this change is preferable for two reasons. First, if you are repeatedly ORing containers together, you'll only trigger the slow mode at most once. The current code can repeatedly take the bitmap path and then convert back to arrays. Secondly, the new code is somewhat simpler.

It does make some things slower, so I'm curious to hear if people are comfortable with that change.

current:
```
BenchmarkArrayIorMergeThreshold/mostly-overlap-12	71218	16349 ns/op
BenchmarkArrayIorMergeThreshold/little-overlap-12	75625	16343 ns/op
BenchmarkArrayIorMergeThreshold/no-overlap-12		110556	11090 ns/op
```
with change 
```
BenchmarkArrayIorMergeThreshold/mostly-overlap-12	138745	7968 ns/op
BenchmarkArrayIorMergeThreshold/little-overlap-12	122030	10970 ns/op
BenchmarkArrayIorMergeThreshold/no-overlap-12		67244	20027 ns/op
```

### CODE REVIEW

**Comment by lemire** [comment]
Comments are invited.

**Comment by lemire** [comment]
Your reasoning is sound, but I'd really want other folks to discuss this because it is not going to be a net positive.

**Comment by guymolinari** [comment]
I would agree.  Don't see a significant benefit.

**Comment by jacksonrnewhouse** [comment]
The main benefit is that if you OR together a bunch of containers that each stay below 4096 you'll only do the expensive thing once. The current implementation will repeatedly map to bitmap containers and then convert back. It's a lot harder to imagine a reasonable antagonistic case where you pay a penalty for not preemptively converting to a bitmap.

**Comment by lemire** [comment]
> The main benefit is that if you OR together a bunch of containers that each stay below 4096 you'll only do the expensive thing once. The current implementation will repeatedly map to bitmap containers and then convert back. It's a lot harder to imagine a reasonable antagonistic case where you pay a penalty for not preemptively converting to a bitmap.

That sounds credible.

Your argument is that we should be optimistic that we won't need to do new allocation. Is that it?

**Comment by jacksonrnewhouse** [comment]
Yep, that's the idea.

**Comment by jacksonrnewhouse** [comment]
Took another stab at this I'll be putting up in a new PR.

**Pull request closed without merging**
