### PR TITLE
Unification of bitmap unserialization by using auxiliary byteInput approach

### PR DESCRIPTION
**Pull request by alldroll**
This pull request is not aimed to be merged, it should be treated as a proposal for enhancement.

Currently, bitmap package has two cases that I would like to consider:

* Methods `readFrom/fromBuffer` are responsible for restoring bitmap's state from `io.Reader` and `byte slice`. They have pretty the same code base and each of them has own cons. 

* `fromBuffer` makes a user keep (to hold reference) the provided byte slice and also to leave it constant. 

* `readFrom` loses the performance due to the necessity to create objects from the read byte data.

This pull request tries to solve these issues. For unification was implemented the auxiliary class `byteInput` for io utils. Also, in `roaringArray` was added special field `sentry` that holds the references of `allocated/type converted` slices (here I am not sure about this approach, in theory, it should work and all we need to ask a user to keep the provided `buf` immutable).

### CODE REVIEW

**Comment by lemire** [comment]
The goal is reduce the logic duplication. Do I understand correctly?

**Comment by alldroll** [comment]
Yes, also possibly save a user from the need to hold a reference on `buf` byte slice for method `FromBuffer`

**Comment by lemire** [comment]
This looks like an interesting design!

1. How do you handle big endian systems. The Roaring format is little endian, and bytes must be flipped on big endian systems...

2. You have deleted some tests without adding new ones... ideally we want more testing over time, not less...

3. You claim that this change would free us from having to hold on to the slice with FromBuffer. Can you elaborate? I You either have to make a copy or hold on to a reference.

4. Your code is more elegant and maintainable. This is important but we don’t want to sacrifice performance. Have you checked the performance? Before merging this, we would want to make sure that there is no performance regression.

**Comment by alldroll** [comment]
I totally agree with you, I have no questions about 2,3,4 cases. But could you describe more the case with `big endian systems` . How was it handled before? All I have done is just leave only `FromBuffer` implementation with `bytesBuffer` instead of `byte slice`.

**Comment by lemire** [comment]
Look at the file diff ... we had calls to binary.LittleEndian.Uint16 on big endian systems. This may be gone.

I think we don’t test on big endian systems in the CI.

**Comment by lemire** [comment]
We need to find a way to test on big endian.

How is the performance in your tests!

**Comment by lemire** [comment]
Ok. I have done some reading and it appears that Go does not yet support big endian systems (which are uncommon anyhow) so let us forget about the endianness question.

**Comment by alldroll** [comment]
I wrote some benchmarks, here it is

```
benchmark                                               old ns/op     new ns/op     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             1367          1031          -24.58%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            5024          3014          -40.01%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           5175          2939          -43.21%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          14214         5055          -64.44%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         66036         19665         -70.22%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         166           236           +42.17%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        157           263           +67.52%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       166           280           +68.67%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      1034          1378          +33.27%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     8363          11271         +34.77%

benchmark                                               old allocs     new allocs     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             14             11             -21.43%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            14             11             -21.43%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           14             11             -21.43%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          94             38             -59.57%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         823            308            -62.58%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         4              5              +25.00%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        4              5              +25.00%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       4              5              +25.00%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      13             14             +7.69%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     103            104            +0.97%

benchmark                                               old bytes     new bytes     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             1614          1540          -4.58%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            8423          8324          -1.18%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           8422          8324          -1.16%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          18223         9096          -50.09%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         32625         16794         -48.52%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         52            84            +61.54%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        52            84            +61.54%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       52            84            +61.54%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      672           704           +4.76%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     6896          6928          +0.46%
```
I can't say, that this pull request really does а good job, as we could see, we have some performance benefits for `ReadFrom` method, but also have a slight reduction for `FromBuffer`

Also, I do have concern for the method `byteBufferAdapter.next()`. Here we allocate a new memory block for each call and use `byteSliceAsUint16Slice` instead of creating new objects [as here](https://github.com/alldroll/roaring/blob/master/roaringarray.go#L721). I can't find any proof that this will work properly and Go will keep a reference on the allocated memory block. I tried to catch it in tests `TestHoldReference`, but it seems to me that I do something wrong because of misunderstanding how Go works with memory.

**Comment by lemire** [comment]
Thanks for the thorough benchmarks. I particularly appreciate the various metrics you have used.

I think you have shown that your PR has potential value and should be pursued as you improve very significantly the performance. Of course, we may ask whether it is safe...

Can't we test what happens with the garbage collector with `runtime.GC()`. It may not be perfect, but I think it could help stress your test.

You have a small performance with FromBuffer. Any chance we can narrow down the source of this performance regression? I think it should be possible, in theory at least, to have no performance degradation.

I think it would be acceptable to see a small (say 5%) performance regression given that we cut down the number of lines and thus improve maintainability. We probably want to avoid a performance degradation of more than 10%...

Please keep going... this looks very promising!

**Comment by lemire** [comment]
My gut feeling is that methods like `readUInt32()` might be where the performance degradation comes from.

**Comment by alldroll** [comment]
You are right. I have optimized `readUInt32`, `readUInt16`, `next` methods, and we have some achievement performance, but it is not sufficient yet
```
benchmark                                               old ns/op     new ns/op     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             822           614           -25.30%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            2823          1734          -38.58%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           2856          1753          -38.62%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          8338          3044          -63.49%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         43401         14037         -67.66%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         125           178           +42.40%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        121           176           +45.45%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       121           176           +45.45%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      643           777           +20.84%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     5378          6180          +14.91%
```

I carry on working on it...

**Comment by lemire** [comment]
It is close!!!

**Comment by lemire** [comment]
Thanks for adding runtime.GC, this gives us extra confidence.

**Comment by seebs** [comment]
Go's byte encoding stuff supports big/little endian data structures. But if you want to just cast bytes to something else, yeah, you are relying on the target being little-endian.

Our implementation has some magic to encourage the use of memory-mapped backing store where possible; one of the key realizations being that if you have memory-mapped storage, referring to a slice of it doesn't necessarily imply any disk activity at all until the slice actually gets accessed.

**Comment by lemire** [comment]
> you are relying on the target being little-endian

Yes, but unless I am wrong, Go only runs on little endian... so we can safely assume that the system is little endian.

**Comment by seebs** [comment]
I think it's currently true, but every time I've said "I don't need to worry about endianness" in the past, I've gotten bitten by it later, so I've gotten to be a little distrustful of that instinct. The good news is that the encoding/binary stuff is basically free when you're using platform order, the bad news is, it does imply copies, and of course, the real win is trying to avoid the copies.

**Comment by lemire** [comment]
@seebs I am skeptical of the value of supporting hypothetical systems we cannot test on. If some big-endian Go implementation came out, my instincts would tell me that we have bugs...

So it is probably best to wait and see... if one such platform comes up, we will start supporting it...

**Comment by maciej** [comment]
`byteSliceAsUint*Slice` function family has both a _generic_ implementation and a _little-endian_ specific one. From my understanding the _generic_ one got created for Google App Engine where access to `unsafe` package is prohibited.
However in the generic case bytes slices are converted to uint* slices by created a copy and reading the input slice using `binary.LittleEndian`. Therefore those functions would probably be fine on any big-endian systems.

Skimming over the PR code I saw that the functions implementing `readUint*` of the `byteInput` interface decode the input using `binary.LittleEndian` functions as well.

Based on that I don't see any place where big-endian systems were to be unsupported by design in this PR.

@alldroll the PR is very promising!

**Comment by alldroll** [comment]
I've done some investigation and found that the cause of performance regression is an allocation of a new object byteInput. Unfortunately, I have no idea how to make it faster, there is only one thing came to my mind - using sync.Pool. This approach makes me concerned because of the code became more complex and confusing. Here are new benchmarks

```
benchmark                                               old ns/op     new ns/op     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             1367          692           -49.38%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            5024          2428          -51.67%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           5175          2356          -54.47%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          14214         4886          -65.63%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         66036         22769         -65.52%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         166           214           +28.92%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        157           212           +35.03%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       166           206           +24.10%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      1034          1071          +3.58%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     8363          9360          +11.92%
```

**Comment by lemire** [comment]
@maciej How can we test compatibility with the Google App Engine... short of doing so manually? I'd like to make sure that this PR does not break someone's code... any way to disable Unsafe as part of our CI tests?

**Comment by maciej** [comment]
@lemire  `go test -tags appengine ./...` should do the trick

**Comment by maciej** [comment]
Out of curiosity I've checked how `BenchmarkUnmarshalBinary` performs both with and without `appengine` tag. There clearly is a difference.

```
⋊> ~/P/roaring on master ⨯ go test -bench 'BenchmarkUnmarshalBinary' -run '-' -v | prettybench
goos: darwin
goarch: amd64
pkg: github.com/RoaringBitmap/roaring
PASS
benchmark                     iter      time/iter   bytes alloc          allocs
---------                     ----      ---------   -----------          ------
BenchmarkUnmarshalBinary-8   30000    42.65 μs/op   155359 B/op   337 allocs/op
ok  	github.com/RoaringBitmap/roaring	1.875s
⋊> ~/P/roaring on master ⨯ go test -tags appengine -bench 'BenchmarkUnmarshalBinary' -run '-' -v | prettybench
goos: darwin
goarch: amd64
pkg: github.com/RoaringBitmap/roaring
PASS
benchmark                    iter       time/iter   bytes alloc          allocs
---------                    ----       ---------   -----------          ------
BenchmarkUnmarshalBinary-8   5000    368.12 μs/op   299431 B/op   643 allocs/op
ok  	github.com/RoaringBitmap/roaring	1.978s
```

**Comment by lemire** [comment]
@maciej  thank you.

**Comment by lemire** [comment]
@maciej  That's a huge difference. 

We probably want to benchmark both.

**Comment by alldroll** [comment]
@lemire 

I've run the same benchmarks with a flag `-tags appengine` and here is what we got:

```
benchmark                                               old ns/op     new ns/op     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             5503          2804          -49.05%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            13344         7364          -44.81%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           13721         6750          -50.81%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          22866         9661          -57.75%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         75620         28100         -62.84%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         1984          1978          -0.30%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        4231          4834          +14.25%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       4299          4382          +1.93%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      5892          6694          +13.61%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     16862         17084         +1.32%

benchmark                                               old allocs     new allocs     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             16             12             -25.00%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            16             12             -25.00%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           16             12             -25.00%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          96             48             -50.00%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         825            408            -50.55%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         6              6              +0.00%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        6              6              +0.00%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       6              6              +0.00%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      24             24             +0.00%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     204            204            +0.00%

benchmark                                               old bytes     new bytes     delta
BenchmarkUnserializeReadFrom/ReadFrom-650-8             3059          2936          -4.02%
BenchmarkUnserializeReadFrom/ReadFrom-6500-8            16672         16508         -0.98%
BenchmarkUnserializeReadFrom/ReadFrom-65000-8           16671         16508         -0.98%
BenchmarkUnserializeReadFrom/ReadFrom-650000-8          26476         17364         -34.42%
BenchmarkUnserializeReadFrom/ReadFrom-6500000-8         40868         25791         -36.89%
BenchmarkUnserializeFromBuffer/FromBuffer-650-8         1464          1464          +0.00%
BenchmarkUnserializeFromBuffer/FromBuffer-6500-8        8248          8250          +0.02%
BenchmarkUnserializeFromBuffer/FromBuffer-65000-8       8248          8250          +0.02%
BenchmarkUnserializeFromBuffer/FromBuffer-650000-8      8944          8946          +0.02%
BenchmarkUnserializeFromBuffer/FromBuffer-6500000-8     15900         15904         +0.03%

```

There will no be performance reduction for the `appengine`

**Comment by lemire** [comment]
@alldroll 

Amazing. Thanks for getting these numbers. 

Expect me to merge your PR. I just want to take the time to get my own numbers.

**Comment by lemire** [comment]
Still on my todo.

**Comment by lemire** [comment]
Merging. This is good.

**Pull request merged**
