### PR TITLE
Rewrite tests using one uniform idiom

### LINKED ISSUE #146: Tests should be written using one uniform idiom
We have Convey tests, go1.7 subtests, and basic tests. It works fine, but it is a bit unpleasant.

### PR DESCRIPTION
**Pull request by alldroll**
This resolves #146

### CODE REVIEW

**Comment by lemire** [comment]
I'm all for merging this. Someone wants to have a look?

@maciej @glycerine ?

**Comment by alldroll** [comment]
@lemire I have found the potential problem, in `TestArrayContainerMassiveSetAndGet`, there was a lot of assertion calls (I've some tricky fix, and it helps me). Could you please check it too?

**Comment by lemire** [comment]
This fixes the performance regression...

New numbers:

```
ok  	github.com/RoaringBitmap/roaring	22.190s

real	0m23.471s
user	0m24.784s
sys	0m0.176s
```

**Comment by lemire** [comment]
Merging.

**Pull request merged**
