### PR TITLE
Reduce allocations for iterators

### PR DESCRIPTION
**Pull request by Oppen**
This addresses #94 
The change is simple (and simplistic, some improvements can be done down the line): instead of allocating a new container iterator whenever we change a key, we keep a slot for one of each kind in the outer iterator structure, and we update it and point to it when we switch keys. There's a small constant memory overhead due to this embedding, but overall it should be better for memory pressure than creating and discarding many tiny objects for most bitmaps.

### CODE REVIEW

**Comment by lemire** [comment]
@Oppen It is reasonable. Do you happen to have benchmarks to quantify the benefits?

I am nervous about trusting intuition when it comes to such questions.

**Comment by Oppen** [comment]
Yes, but I'm running more because the confidence interval was rather weak.
For reference, I'm running the following command right now, both on the master branch and this branch:
```shell
for i in {1..100}; do go test -bench='Iter|Advance' -run -; done > bench_iter.new
```
I'll run `benchstat` on the results afterwards and post again.

**Comment by Oppen** [comment]
```
name                                                                 old time/op    new time/op    delta                     
ShortIteratorAdvanceArray/init_size_1_shortIterator_advance-8          62.8ns ±21%    63.7ns ±27%     ~     (p=0.390 n=96+92)
ShortIteratorAdvanceArray/init_size_650_shortIterator_advance-8         111ns ±20%     109ns ±25%     ~     (p=0.071 n=95+93)
ShortIteratorAdvanceArray/init_size_6500_shortIterator_advance-8        126ns ±24%     123ns ±19%   -2.93%  (p=0.015 n=96+91)
ShortIteratorAdvanceArray/init_size_65535_shortIterator_advance-8       134ns ±20%     132ns ±21%     ~     (p=0.213 n=97+95)
ShortIteratorNextArray/init_size_1_shortIterator_next-8                53.0ns ±20%    55.3ns ±20%   +4.38%  (p=0.002 n=91+92)
ShortIteratorNextArray/init_size_650_shortIterator_next-8              2.67µs ±27%    2.48µs ±23%   -6.93%  (p=0.000 n=96+96)
ShortIteratorNextArray/init_size_6500_shortIterator_next-8             25.9µs ±24%    23.7µs ±24%   -8.26%  (p=0.000 n=94+93)
ShortIteratorNextArray/init_size_65535_shortIterator_next-8             255µs ±20%     234µs ±19%   -8.19%  (p=0.000 n=95+88)
IterateRoaring/iterator-compressed-8                                    518µs ±21%     513µs ±19%     ~     (p=0.439 n=98+91)
IterateRoaring/iterator-8                                               519µs ±21%     505µs ±22%   -2.80%  (p=0.029 n=98+93)
IterateRoaring/iterate-compressed-8                                     341µs ±25%     308µs ±23%   -9.85%  (p=0.000 n=96+98)
IterateRoaring/iterate-8                                                363µs ±17%     326µs ±26%  -10.19%  (p=0.000 n=91+99)
SparseIterateRoaring-8                                                  663µs ±23%     568µs ±26%  -14.26%  (p=0.000 n=93+98)
SparseAdvanceRoaring/advance_from_1-8                                   133ns ±20%     109ns ±15%  -18.03%  (p=0.000 n=94+83)  
SparseAdvanceRoaring/advance_from_2-8                                   135ns ±22%     109ns ±13%  -19.07%  (p=0.000 n=93+81)
SparseAdvanceRoaring/advance_from_65-8                                  134ns ±19%     109ns ±17%  -18.74%  (p=0.000 n=93+93)  
SparseAdvanceRoaring/advance_from_650-8                                 135ns ±25%     108ns ±19%  -20.36%  (p=0.000 n=97+89)  
SparseAdvanceOnHugeData-8                                              1.13µs ±27%    0.66µs ±25%  -41.71%  (p=0.000 n=98+97)
SparseAdvanceSequentially/advance_from_1-8                              118µs ± 9%     119µs ±10%     ~     (p=0.807 n=91+87)
SparseAdvanceSequentially/advance_from_2-8                              130µs ±20%     125µs ±20%   -3.89%  (p=0.000 n=90+95)  
SparseAdvanceSequentially/advance_from_65-8                             417µs ±19%     406µs ±18%   -2.61%  (p=0.007 n=89+97)  
SparseAdvanceSequentially/advance_from_650-8                            407µs ±20%     408µs ±23%     ~     (p=0.876 n=93+96)  
IterateBitset-8                                                         233µs ±13%     233µs ±18%     ~     (p=0.434 n=84+93)  
SparseIterateBitset-8                                                  2.19ms ±19%    2.25ms ±20%   +2.83%  (p=0.011 n=93+93) 
ShortIteratorAdvanceBitmap/init_size_1_shortIterator_advance-8         51.5ns ±18%    52.9ns ±21%   +2.66%  (p=0.017 n=95+94)  
ShortIteratorAdvanceBitmap/init_size_650_shortIterator_advance-8       54.2ns ±16%    54.8ns ±18%     ~     (p=0.251 n=91+92)  
ShortIteratorAdvanceBitmap/init_size_6500_shortIterator_advance-8      54.7ns ±21%    55.1ns ±16%     ~     (p=0.331 n=94+93)  
ShortIteratorAdvanceBitmap/init_size_65535_shortIterator_advance-8     55.2ns ±19%    54.4ns ±17%     ~     (p=0.276 n=93+92)  
ShortIteratorNextBitmap/init_size_1_shortIterator_next-8                537ns ±25%     793ns ±25%  +47.60%  (p=0.000 n=94+92)  
ShortIteratorNextBitmap/init_size_650_shortIterator_next-8             4.51µs ±23%    4.79µs ±22%   +6.27%  (p=0.000 n=96+93)
ShortIteratorNextBitmap/init_size_6500_shortIterator_next-8            39.5µs ±16%    40.7µs ±24%   +3.14%  (p=0.012 n=95+95)  
ShortIteratorNextBitmap/init_size_65535_shortIterator_next-8            390µs ±21%     409µs ±19%   +4.81%  (p=0.000 n=94+94)  
ShortIteratorAdvanceRuntime/init_size_1_shortIterator_advance-8        53.7ns ±19%    54.8ns ±18%     ~     (p=0.053 n=89+91)
ShortIteratorAdvanceRuntime/init_size_650_shortIterator_advance-8      63.2ns ±22%    63.7ns ±25%     ~     (p=0.466 n=93+94)
ShortIteratorAdvanceRuntime/init_size_6500_shortIterator_advance-8     63.6ns ±18%    63.8ns ±21%     ~     (p=0.489 n=92+93)  
ShortIteratorAdvanceRuntime/init_size_65535_shortIterator_advance-8    63.9ns ±16%    63.7ns ±20%     ~     (p=0.893 n=87+94)  
ShortIteratorNextRuntime/init_size_1_shortIterator_next-8              50.9ns ±20%    49.2ns ±26%   -3.34%  (p=0.008 n=93+93)  
ShortIteratorNextRuntime/init_size_650_shortIterator_next-8            4.07µs ±29%    3.91µs ±28%   -4.09%  (p=0.004 n=97+94)  
ShortIteratorNextRuntime/init_size_6500_shortIterator_next-8           38.6µs ±29%    38.1µs ±26%     ~     (p=0.482 n=94+95)  
ShortIteratorNextRuntime/init_size_65535_shortIterator_next-8           383µs ±20%     386µs ±29%     ~     (p=0.719 n=93+98)  
                                                                                                                           
name                                                                 old alloc/op   new alloc/op   delta                     
IterateRoaring/iterator-compressed-8                                    96.0B ± 0%    112.0B ± 0%  +16.67%  (p=0.000 n=100+100)
IterateRoaring/iterator-8                                               96.0B ± 0%    112.0B ± 0%  +16.67%  (p=0.000 n=100+100)
IterateRoaring/iterate-compressed-8                                     0.00B          0.00B          ~     (all equal)      
IterateRoaring/iterate-8                                                0.00B          0.00B          ~     (all equal)      
SparseAdvanceRoaring/advance_from_1-8                                   64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceRoaring/advance_from_2-8                                   64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceRoaring/advance_from_65-8                                  64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceRoaring/advance_from_650-8                                 64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceOnHugeData-8                                                457B ±26%      112B ± 0%  -75.49%  (p=0.000 n=99+100) 
SparseAdvanceSequentially/advance_from_1-8                              64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_2-8                              64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_65-8                             64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_650-8                            64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=100+100)
                                                                                                                               
name                                                                 old allocs/op  new allocs/op  delta                       
IterateRoaring/iterator-compressed-8                                     4.00 ± 0%      1.00 ± 0%  -75.00%  (p=0.000 n=100+100)
IterateRoaring/iterator-8                                                4.00 ± 0%      1.00 ± 0%  -75.00%  (p=0.000 n=100+100)
IterateRoaring/iterate-compressed-8                                      0.00           0.00          ~     (all equal)        
IterateRoaring/iterate-8                                                 0.00           0.00          ~     (all equal)        
SparseAdvanceRoaring/advance_from_1-8                                    2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceRoaring/advance_from_2-8                                    2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceRoaring/advance_from_65-8                                   2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceRoaring/advance_from_650-8                                  2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceOnHugeData-8                                                19.5 ±28%       1.0 ± 0%  -94.88%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_1-8                               2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_2-8                               2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_65-8                              2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
SparseAdvanceSequentially/advance_from_650-8                             2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=100+100)
```

**Comment by lemire** [comment]
@Oppen What is up with this line...

```
ShortIteratorNextBitmap/init_size_1_shortIterator_next-8                537ns ±25%     793ns ±25%  +47.60%  (p=0.000 n=94+92)  
```

**Comment by Oppen** [comment]
I _guess_ it's caused by the extra memset and copy from embedding the structures. For a single element it may very well offset creating a single iterator on the heap. I could profile the benchmark for both versions to make sure. If that's really the cause, making it closer to the C implementation may help by reducing how many extra bytes the initialization needs to deal with. Note the difference is about 250ns, even if the percentage is high.

**Comment by lemire** [comment]
@Oppen I am willing to merge this if you recommend it.

**Comment by Oppen** [comment]
There's something odd. Those benchmarks are for just containers, and the iterators for those are created with `getShortIterator`, which is unmodified. I'm looking into it because it doesn't make sense that we observe any kind of change there.

**Comment by Oppen** [comment]
The relevant code:
https://github.com/Oppen/roaring/blob/issue_94/container_test.go#L170-L199 (actual implementation of the benchmark)
https://github.com/Oppen/roaring/blob/issue_94/bitmapcontainer_test.go#L206-L208 (the callsite)

**Comment by Oppen** [comment]
> @Oppen I am willing to merge this if you recommend it.

The change should be harmless enough, but I'm not comfortable with not understanding why it affected that benchmark.

**Comment by Oppen** [comment]
Added simple test and benchmarks:
```
$ go test -bench Checksum -run -
goos: linux
goarch: amd64
pkg: github.com/RoaringBitmap/roaring
cpu: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
BenchmarkChecksum/checksum-1-8          1000000000               0.0000004 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-1-8               1000000000               0.0000003 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-2-8                          1000000000               0.0000003 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-2-8               1000000000               0.0000003 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-4-8                          1000000000               0.0000003 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-4-8               1000000000               0.0000003 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-8-8                          1000000000               0.0000004 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-8-8               1000000000               0.0000005 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-16-8                         1000000000               0.0000005 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-16-8              1000000000               0.0000005 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-32-8                         1000000000               0.0000006 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-32-8              1000000000               0.0000005 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-64-8                         1000000000               0.0000006 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-64-8              1000000000               0.0000005 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-128-8                        1000000000               0.0000010 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-128-8             1000000000               0.0000008 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-256-8                        1000000000               0.0000011 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-256-8             1000000000               0.0000010 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-512-8                        1000000000               0.0000016 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-512-8             1000000000               0.0000019 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-1024-8                       1000000000               0.0000028 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-1024-8            1000000000               0.0000029 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-2048-8                       1000000000               0.0000051 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-2048-8            1000000000               0.0000056 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-4096-8                       1000000000               0.0000100 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-4096-8            1000000000               0.0000104 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-8192-8                       1000000000               0.0000196 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-8192-8            1000000000               0.0000201 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-16384-8                      1000000000               0.0000395 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-16384-8           1000000000               0.0000388 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-32768-8                      1000000000               0.0000765 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-32768-8           1000000000               0.0000774 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-65536-8                      1000000000               0.0001477 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-65536-8           1000000000               0.0001500 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-131072-8                     1000000000               0.0001505 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-131072-8          1000000000               0.0001542 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-262144-8                     1000000000               0.0001815 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-262144-8          1000000000               0.0001547 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-524288-8                     1000000000               0.0001551 ns/op               0 B/op          0 allocs/op
BenchmarkChecksum/checksum-compressed-524288-8          1000000000               0.0001554 ns/op               0 B/op          0 allocs/op
PASS
ok      github.com/RoaringBitmap/roaring        0.150s
```

**Comment by Oppen** [comment]
I rebased against current HEAD and run the benchmarks again 30 times each. I ran the new version first, master later. The results changed as follows:
```
name                                                                 old time/op    new time/op    delta                     
ShortIteratorAdvanceArray/init_size_1_shortIterator_advance-8          57.1ns ±16%    56.5ns ±17%     ~     (p=0.322 n=29+29)
ShortIteratorAdvanceArray/init_size_650_shortIterator_advance-8        87.0ns ±14%    88.2ns ±12%     ~     (p=0.323 n=30+28)
ShortIteratorAdvanceArray/init_size_6500_shortIterator_advance-8       98.9ns ±16%    99.0ns ±10%     ~     (p=0.638 n=29+28)
ShortIteratorAdvanceArray/init_size_65535_shortIterator_advance-8       105ns ±15%     104ns ± 6%     ~     (p=0.924 n=29+25)
ShortIteratorNextArray/init_size_1_shortIterator_next-8                46.7ns ±18%    47.4ns ±16%     ~     (p=0.495 n=30+29)
ShortIteratorNextArray/init_size_650_shortIterator_next-8              1.99µs ±19%    2.20µs ±17%  +10.59%  (p=0.000 n=29+29)
ShortIteratorNextArray/init_size_6500_shortIterator_next-8             19.8µs ±18%    22.1µs ±17%  +11.44%  (p=0.000 n=29+30)
ShortIteratorNextArray/init_size_65535_shortIterator_next-8             203µs ±20%     219µs ±10%   +8.26%  (p=0.000 n=29+28)
IterateRoaring/iterator-compressed-8                                    425µs ±20%     445µs ± 5%     ~     (p=0.082 n=28+25)
IterateRoaring/iterator-8                                               435µs ±26%     437µs ± 7%     ~     (p=0.535 n=29+25)
IterateRoaring/iterate-compressed-8                                     259µs ±20%     274µs ± 4%   +5.85%  (p=0.007 n=29+26)
IterateRoaring/iterate-8                                                285µs ±26%     315µs ±12%  +10.84%  (p=0.000 n=28+29)
SparseIterateRoaring-8                                                  498µs ±27%     458µs ±11%   -7.99%  (p=0.003 n=29+29)
SparseAdvanceRoaring/advance_from_1-8                                   110ns ±19%      85ns ± 7%  -23.05%  (p=0.000 n=28+28)
SparseAdvanceRoaring/advance_from_2-8                                   112ns ±27%      89ns ±24%  -20.92%  (p=0.000 n=28+29)
SparseAdvanceRoaring/advance_from_65-8                                  109ns ±15%      92ns ±23%  -16.26%  (p=0.000 n=28+30)
SparseAdvanceRoaring/advance_from_650-8                                 108ns ±19%      92ns ±24%  -15.01%  (p=0.000 n=27+30)
SparseAdvanceOnHugeData-8                                              1.04µs ±16%    0.68µs ±12%  -34.80%  (p=0.000 n=28+27)
SparseAdvanceSequentially/advance_from_1-8                              119µs ± 6%     120µs ± 4%     ~     (p=0.188 n=29+29)
SparseAdvanceSequentially/advance_from_2-8                              113µs ±10%     114µs ± 3%     ~     (p=0.940 n=29+26)
SparseAdvanceSequentially/advance_from_65-8                             345µs ±18%     373µs ± 7%   +8.28%  (p=0.000 n=29+28)
SparseAdvanceSequentially/advance_from_650-8                            342µs ±28%     366µs ± 5%   +6.86%  (p=0.002 n=30+26)
IterateBitset-8                                                         200µs ±24%     198µs ± 5%     ~     (p=0.527 n=29+25)
SparseIterateBitset-8                                                  1.93ms ±14%    1.87ms ± 4%   -3.09%  (p=0.011 n=28+25)
ShortIteratorAdvanceBitmap/init_size_1_shortIterator_advance-8         42.7ns ±17%    42.2ns ± 9%     ~     (p=0.666 n=30+27)
ShortIteratorAdvanceBitmap/init_size_650_shortIterator_advance-8       45.4ns ±16%    45.0ns ±14%     ~     (p=0.455 n=29+29)
ShortIteratorAdvanceBitmap/init_size_6500_shortIterator_advance-8      45.2ns ±18%    44.6ns ±13%     ~     (p=0.516 n=30+26)
ShortIteratorAdvanceBitmap/init_size_65535_shortIterator_advance-8     45.2ns ±20%    44.4ns ± 8%     ~     (p=0.240 n=30+27)
ShortIteratorNextBitmap/init_size_1_shortIterator_next-8                629ns ±15%     419ns ± 4%  -33.31%  (p=0.000 n=29+24)
ShortIteratorNextBitmap/init_size_650_shortIterator_next-8             3.98µs ±17%    3.76µs ±10%   -5.46%  (p=0.001 n=30+27)
ShortIteratorNextBitmap/init_size_6500_shortIterator_next-8            34.1µs ±13%    34.2µs ±11%     ~     (p=0.464 n=29+27)
ShortIteratorNextBitmap/init_size_65535_shortIterator_next-8            336µs ±10%     337µs ± 8%     ~     (p=0.457 n=24+25)
ShortIteratorAdvanceRuntime/init_size_1_shortIterator_advance-8        46.8ns ±15%    46.4ns ±14%     ~     (p=0.514 n=29+29)
ShortIteratorAdvanceRuntime/init_size_650_shortIterator_advance-8      52.6ns ±23%    52.3ns ±14%     ~     (p=0.918 n=30+30)
ShortIteratorAdvanceRuntime/init_size_6500_shortIterator_advance-8     52.4ns ±16%    52.7ns ±10%     ~     (p=0.363 n=29+30)
ShortIteratorAdvanceRuntime/init_size_65535_shortIterator_advance-8    52.3ns ±12%    53.2ns ±12%     ~     (p=0.149 n=30+29)
ShortIteratorNextRuntime/init_size_1_shortIterator_next-8              42.9ns ±14%    42.8ns ±12%     ~     (p=0.844 n=29+30)
ShortIteratorNextRuntime/init_size_650_shortIterator_next-8            3.23µs ±15%    3.25µs ±10%     ~     (p=0.655 n=29+26)
ShortIteratorNextRuntime/init_size_6500_shortIterator_next-8           32.1µs ±24%    31.7µs ± 7%     ~     (p=0.445 n=29+25)
ShortIteratorNextRuntime/init_size_65535_shortIterator_next-8           325µs ±22%     320µs ± 8%     ~     (p=0.279 n=29+26)

name                                                                 old alloc/op   new alloc/op   delta
IterateRoaring/iterator-compressed-8                                    96.0B ± 0%    112.0B ± 0%  +16.67%  (p=0.000 n=30+30)
IterateRoaring/iterator-8                                               96.0B ± 0%    112.0B ± 0%  +16.67%  (p=0.000 n=30+30)
IterateRoaring/iterate-compressed-8                                     0.00B          0.00B          ~     (all equal)
IterateRoaring/iterate-8                                                0.00B          0.00B          ~     (all equal)
SparseAdvanceRoaring/advance_from_1-8                                   64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceRoaring/advance_from_2-8                                   64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceRoaring/advance_from_65-8                                  64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceRoaring/advance_from_650-8                                 64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceOnHugeData-8                                                549B ±20%      112B ± 0%  -79.59%  (p=0.000 n=28+30)
SparseAdvanceSequentially/advance_from_1-8                              64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_2-8                              64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_65-8                             64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_650-8                            64.0B ± 0%    112.0B ± 0%  +75.00%  (p=0.000 n=30+30)

name                                                                 old allocs/op  new allocs/op  delta
IterateRoaring/iterator-compressed-8                                     4.00 ± 0%      1.00 ± 0%  -75.00%  (p=0.000 n=30+30)
IterateRoaring/iterator-8                                                4.00 ± 0%      1.00 ± 0%  -75.00%  (p=0.000 n=30+30)
IterateRoaring/iterate-compressed-8                                      0.00           0.00          ~     (all equal)
IterateRoaring/iterate-8                                                 0.00           0.00          ~     (all equal)
SparseAdvanceRoaring/advance_from_1-8                                    2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceRoaring/advance_from_2-8                                    2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceRoaring/advance_from_65-8                                   2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceRoaring/advance_from_650-8                                  2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceOnHugeData-8                                                23.8 ±24%       1.0 ± 0%  -95.79%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_1-8                               2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_2-8                               2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_65-8                              2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
SparseAdvanceSequentially/advance_from_650-8                             2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=30+30)
```

Specifically, the one test that took 40% longer before takes 30% less time now, so I can only guess, given the order of magnitude of time (nsecs) that the difference is due to throttling or scheduling effects.
I feel more comfortable merging now.

I'd like to make some improvements to tend to zero-alloc or at least make allocs smaller (for example, by keeping only one index into the container instead of one per iterator), but that can be done in a future PR.

**Comment by lemire** [comment]
This looks good but might I suggest you explain the rationale in the code with a comment. I am concerned that others might be puzzled by the code.

**Comment by lemire** [comment]
Basically just copy/paste your rationale as a comment.

**Comment by Oppen** [comment]
OK, that makes a lot of sense.

**Comment by Oppen** [comment]
Comment added as amend commit.

**Comment by lemire** [comment]
Merged!

**Pull request merged**
