### PR TITLE
Fix several panics from buffer-overruns in *Bitmap.FromBuffer

### PR DESCRIPTION
**Pull request by maciej**
Fixes #171

### CODE REVIEW

**Comment by lemire** [comment]
Waiting for travis.

**Comment by dgryski** [comment]
Once this lands we should rerun the fuzz tests I added to see if anything else gets picked up.

**Comment by lemire** [comment]
@maciej Should we expect this PR to clear the tests?

We have a failing CI.

**Comment by dgryski** [comment]
From: https://travis-ci.org/RoaringBitmap/roaring/jobs/363798269#L2557

```
serialization_test.go:1002: crasher testdata/crashproneinput2.bin panicked: runtime error: slice bounds out of range
```

**Comment by maciej** [comment]
@lemire @dgryski it fails on "GOARCH=386 go test" which I haven't tested locally! I can't get to it at the moment, but I'll fix that soon!

**Comment by lemire** [comment]
Let us merge this then since it should make the code better.

**Pull request merged**
