### PR TITLE
Add Reverse Iterators - resolves issue #185 allow backward iteration …

### PR DESCRIPTION
**Pull request by joenall**
Added reverse iterators. PrevSetBit is not using math/bits and may be improvable. Test coverage is good and all tests pass. Feedback on names and style are welcome.

### CODE REVIEW

**Comment by maciej** [comment]
looks got to me

**Comment by lemire** [comment]
@maciej's recommendation is good to have. Let me see.

**Comment by lemire** [comment]
It is "improvable" but a great basis. Merging.

**Comment by lemire** [comment]
I only made a small change (regarding the bitset containers) and then released it. Basically, Joe did all the hard work.

**Pull request merged**
